# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(
    0,
    os.path.abspath(os.path.join('/'.join(os.getcwd().split('/')[:-2])
        , 'reader_lib/'))
)
sys.path.insert(
    0,
    os.path.abspath(os.path.join('/'.join(os.getcwd().split('/')[:-2])
        , 'writer_lib/'))
)



# -- Project information -----------------------------------------------------

project = 'Will Feature Store'
copyright = '2021, Will Data Team'
author = 'Will Data Team'


pdf_documents = [('index', u'rst2pdf', u'Sample rst2pdf doc', u'Your Name'),]
html_sidebars = {'**': [
    'globaltoc.html',
    'relations.html',
    'sourcelink.html',
    'searchbox.html'
]}
# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.


extensions = ['sphinx.ext.todo', 'sphinx.ext.viewcode', 'sphinx.ext.autodoc',
              'sphinx.ext.autosectionlabel', 'rst2pdf.pdfbuilder',
              'sphinxcontrib.confluencebuilder']

autoclass_content = 'both'
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#fd0',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}
html_css_files = ["custom_will_theme.css"]

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}


confluence_publish = True
confluence_space_name = 'WFS'
# (for Confluence Cloud)
confluence_server_url = 'https://contameupag.atlassian.net/wiki/'
confluence_server_user = os.environ['CONFLUENCE_EMAIL']
confluence_server_pass = os.environ['CONFLUENCE_KEY']
confluence_disable_rest = True
confluence_parent_page = 'Will Feature Store Home'
#confluence_publish_dryrun = True
confluence_page_hierarchy = True